name: hf-hybrid-recs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - pip:
      - scikit-surprise==1.1.4
      - requests>=2.31.0,<3
      - gradio==4.44.0
